INSERT INTO `inspired-nomad-455114-k3.cz_api_coincap.cz_coincap_crypto` (
  ID_CRIPTO,
  NR_POSICAO_RANK,
  DS_SIGLA_ATIVO,
  NM_ATIVO,
  QT_EM_CIRCULACAO,
  QT_MAXIMA_EMISSAO,
  VL_CAPITALIZACAO_MERCADO,
  VL_VOLUME_24H,
  VL_PRECO_ATUAL,
  PC_VARIACAO_24H,
  VL_PRECO_MEDIO_24H,
  LINK_EXPLORADOR,
  DT_CONSULTA
)
SELECT
  ID_CRIPTO,
  NR_POSICAO_RANK,
  DS_SIGLA_ATIVO,
  NM_ATIVO,
  QT_EM_CIRCULACAO,
  QT_MAXIMA_EMISSAO,
  VL_CAPITALIZACAO_MERCADO,
  VL_VOLUME_24H,
  VL_PRECO_ATUAL,
  PC_VARIACAO_24H,
  VL_PRECO_MEDIO_24H,
  LINK_EXPLORADOR,
  FORMAT_TIMESTAMP('%d/%m/%Y %H:%M:%S', CURRENT_TIMESTAMP(), 'America/Sao_Paulo') AS DT_CONSULTA
FROM `inspired-nomad-455114-k3.sz_api_coincap.sz_coincap_crypto`
WHERE ID_CRIPTO IS NOT NULL;
